# OAuth provider credentials (DEV local file)
# Priority order in app: JVM -D > ENV VAR > this file

# Google OAuth
oauth.google.client.id=
oauth.google.client.secret=

# Facebook OAuth
oauth.facebook.client.id=
oauth.facebook.client.secret=
